bot:
  admin:
    admin_id: 778024940158844938
    admin_name: BWP09#5091
  embed_color: 40863
  id: 947343189352796220
  megaspam_max: 20
  playing_status: Type "hesa help"
  purge_max: 10
  version: R2.0.0 D11.10.22
emoji:
  no_emoji: "\u274C"
  yes_emoji: "\u2705"
files:
  ffmpeg_exec_path: C:/Program Files (extracted)/ffmpeg-n5.0-latest-win64-gpl-5.0/bin/ffmpeg.exe
  help_files_path: C:/Users/BWP09/Desktop/Misc/Code/Python/Discord/Bots/Hes_a_BOT_v2/config/help/
  images_path: C:/Users/BWP09/Desktop/Misc/Code/Python/Discord/Bots/Hes_a_BOT_v2/data/images/
  logs_path: C:/Users/BWP09/Desktop/Misc/Code/Python/Discord/Bots/Hes_a_BOT_v2/logs/logs/
  snipe_path: C:/Users/BWP09/Desktop/Misc/Code/Python/Discord/Bots/Hes_a_BOT_v2/logs/snipe/
  syntax_files_path: C:/Users/BWP09/Desktop/Misc/Code/Python/Discord/Bots/Hes_a_BOT_v2/config/syntax_help/
  vc_download_path: C:/Users/BWP09/Desktop/Misc/Code/Python/Discord/Bots/Hes_a_BOT_v2/data/vc_files/yt_download/
  vc_files_path: C:/Users/BWP09/Desktop/Misc/Code/Python/Discord/Bots/Hes_a_BOT_v2/data/vc_files/
  blacklist_path: C:/Users/BWP09/Desktop/Misc/Code/Python/Discord/Bots/Hes_a_BOT_v2/config/blacklist/
snipe_message: '[11-06-2022 00:16:29]: [Pynoly Development: general]: BWP09: hesa
  megaspam 10; 1'
